version : '3.7'

services:
    nginx:
        container_name: nginx
        image: nginx:42
        build: requirements/nginx
        depends_on:
            - wordpress
        ports:
            - '443:443'
        volumes:
            - wordpress_2:/var/www/html
        env_file:
            - .env
        restart : unless-stopped
        networks:
            - inception

    mariadb:
        container_name: mariadb
        image: mariadb:42
        build: requirements/mariadb
        env_file:
            - .env
        volumes:
            - mariadb_2:/var/lib/mysql
        restart : unless-stopped
        networks:
            - inception

    wordpress:
        container_name: wordpress
        image: wordpress:6.4.3
        build: requirements/wordpress
        depends_on:
            - mariadb
        volumes:
            - wordpress_2:/var/www/html
        env_file:
            - .env
        restart : unless-stopped
        networks:
            - inception

volumes:
    mariadb_2:
        driver: local
        driver_opts:
            type: none
            device: '/home/rroussel/data_2//mariadb_2'
            o: bind
    wordpress_2:
        driver: local
        driver_opts:
            type: none
            device: '/home/rrousel/data_2/wordpress_2'
            o: bind

networks:
    inception:
        name: inception
